version: '3.8'

services:
  backend:
    container_name: backend-nest-base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    command: yarn run start:dev
